version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=arters_certs
      - DB_PASSWORD=password
      - DB_PORT=5432
      - PORT=3000
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=arters_certs
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
